openapi: 3.0.0
info:
  title: Bantupay API
  version: '1.0'
  x-logo:
    url: images/logo.png
    backgroundColor: '#FFFFFF'
    altText: Bantu logo
  description: This is cool
  contact:
    name: Bantypay
servers:
  - url: 'https://api-testnet.bantupay.org'
paths:
  /v1/user/location/info:
    get:
      summary: Get user info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  currency:
                    type: object
                    properties:
                      alphabetic_code:
                        type: string
                        minLength: 1
                      currency:
                        type: string
                        minLength: 1
                      entity:
                        type: string
                        minLength: 1
                      currency_format:
                        type: object
                        properties:
                          country_currency:
                            type: string
                            minLength: 1
                          currency_description:
                            type: object
                            properties:
                              fraction_size:
                                type: number
                              symbol:
                                type: object
                                properties:
                                  grapheme:
                                    type: string
                                    minLength: 1
                                  template:
                                    type: string
                                    minLength: 1
                                  rtl:
                                    type: boolean
                                required:
                                  - grapheme
                                  - template
                                  - rtl
                            required:
                              - fraction_size
                              - symbol
                        required:
                          - country_currency
                          - currency_description
                    required:
                      - alphabetic_code
                      - currency
                      - entity
                      - currency_format
                  data:
                    type: string
                    minLength: 1
                  geodata:
                    type: object
                    properties:
                      as:
                        type: string
                        minLength: 1
                      city:
                        type: string
                        minLength: 1
                      country:
                        type: string
                        minLength: 1
                      countryCode:
                        type: string
                        minLength: 1
                      isp:
                        type: string
                        minLength: 1
                      lat:
                        type: number
                      lon:
                        type: number
                      org:
                        type: string
                      query:
                        type: string
                        minLength: 1
                      region:
                        type: string
                        minLength: 1
                      regionName:
                        type: string
                        minLength: 1
                      status:
                        type: string
                        minLength: 1
                      timezone:
                        type: string
                        minLength: 1
                      zip:
                        type: string
                      ip:
                        type: string
                        minLength: 1
                    required:
                      - as
                      - city
                      - country
                      - countryCode
                      - isp
                      - lat
                      - lon
                      - org
                      - query
                      - region
                      - regionName
                      - status
                      - timezone
                      - zip
                      - ip
                required:
                  - currency
                  - data
                  - geodata
              examples:
                example:
                  value:
                    currency:
                      alphabetic_code: string
                      currency: string
                      entity: string
                      currency_format:
                        country_currency: string
                        currency_description:
                          fraction_size: 0
                          symbol:
                            grapheme: string
                            template: string
                            rtl: true
                    data: string
                    geodata:
                      as: string
                      city: string
                      country: string
                      countryCode: string
                      isp: string
                      lat: 0
                      lon: 0
                      org: string
                      query: string
                      region: string
                      regionName: string
                      status: string
                      timezone: string
                      zip: string
                      ip: string
      operationId: get-User-Info
      description: Get's geo location information of a user
      tags:
        - Create new user
        - Users
    parameters: []
  /v1/user/account:
    post:
      summary: Create new user
      operationId: post-v1-user-account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: number
                  first_name:
                    type: string
                  last_name:
                    type: string
                  middle_name:
                    type: string
                  username:
                    type: string
                    minLength: 1
                  domain_id:
                    type: number
                  twitter: {}
                  email: {}
                  instagram: {}
                  public_key:
                    type: string
                    minLength: 1
                  ref_code: {}
                  referrer: {}
                  image_thumbnail:
                    type: string
                  country_code:
                    type: string
                    minLength: 1
                  mobile: {}
                  latitude:
                    type: number
                  longitude:
                    type: number
                  currency:
                    type: string
                    minLength: 1
                  alphabetic_code:
                    type: string
                    minLength: 1
                  city:
                    type: string
                    minLength: 1
                  region:
                    type: string
                    minLength: 1
                  region_name:
                    type: string
                    minLength: 1
                  time_zone:
                    type: string
                    minLength: 1
                  isp:
                    type: string
                    minLength: 1
                  account_status:
                    type: number
                required:
                  - id
                  - first_name
                  - last_name
                  - middle_name
                  - username
                  - domain_id
                  - public_key
                  - image_thumbnail
                  - country_code
                  - latitude
                  - longitude
                  - currency
                  - alphabetic_code
                  - city
                  - region
                  - region_name
                  - time_zone
                  - isp
                  - account_status
              examples:
                New user:
                  value:
                    id: 103
                    first_name: John
                    last_name: Wick
                    middle_name: ''
                    username: jwick
                    domain_id: 1
                    twitter: null
                    email: null
                    instagram: null
                    public_key: GCGMGDI2EJQVWCKJNE6DOGB743N7VLWJB7OBHWJ3XJLJPA5FLJGMUHFA
                    ref_code: null
                    referrer: null
                    image_thumbnail: ''
                    country_code: NG
                    mobile: null
                    latitude: 7.1472
                    longitude: 3.3505
                    currency: Naira
                    alphabetic_code: NGN
                    city: Abeokuta
                    region: OG
                    region_name: Ogun State
                    time_zone: Africa/Lagos
                    isp: SP 217
                    account_status: 0
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                Public key already in use:
                  value:
                    error: Public Key Already Exists
                Username already exits:
                  value:
                    error: username already exists
      tags:
        - Users
      description: This endpoint creates a new user with the public key that has been generated. If the user already exsits you get a confict error. Also public key can only be used once.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                username:
                  type: string
                  minLength: 1
                  description: '"newaccount", //or newaccount*domain.org'
                domain_id:
                  type: number
                public_key:
                  type: string
                  minLength: 1
                  description: Public key generated from bantukeypair
              required:
                - username
                - domain_id
                - public_key
            examples:
              New user - success:
                value:
                  username: totally_new_userhere*bantupay.org
                  domain_id: 1
                  public_key: GAOAYQLXKOMRFUDDM26FKDFE6VM72YBW6PE7YD65J74MCZXAPVSEWEYI
              User already exist - fail:
                value:
                  username: jasmine*bantupay.org
                  domain_id: 1
                  public_key: GAOAYQLXKOMRFUDDM26FKDFE6VM72YBW6PE7YD65J74MCZXAPVSEWEYI
        description: ''
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: Create new user
  - name: Users
